export type CodeLanguage =
    'actionscript' |
    'apache_conf' |
    'applescript' |
    'asciidoc' |
    'autohotkey' |
    'batchfile' |
    'c9search' |
    'clojure' |
    'cobol' |
    'coffee' |
    'csharp' |
    'css' |
    'dart' |
    'dockerfile' |
    'dot' |
    'elm' |
    'erlang' |
    'forth' |
    'fortran' |
    'ftl' |
    'gcode' |
    'gherkin' |
    'gitignore' |
    'glsl' |
    'golang' |
    'groovy' |
    'haml' |
    'handlebars' |
    'haskell' |
    'haxe' |
    'html' |
    'ini' |
    'java' |
    'javascript' |
    'json' |
    'jsp' |
    'jssm' |
    'jsx' |
    'julia' |
    'kotlin' |
    'latex' |
    'lean' |
    'less' |
    'liquid' |
    'lisp' |
    'livescript' |
    'lucene' |
    'makefile' |
    'markdown' |
    'mask' |
    'matlab' |
    'mavens_mate_log' |
    'maze' |
    'mel' |
    'mips_assembler' |
    'mysql' |
    'nix' |
    'nsis' |
    'objectivec' |
    'ocaml' |
    'pascal' |
    'perl' |
    'php' |
    'plain_text' |
    'powershell' |
    'praat' |
    'prolog' |
    'properties' |
    'protobuf' |
    'python' |
    'r' |
    'ruby' |
    'rust' |
    'sass' |
    'scad' |
    'scala' |
    'scheme' |
    'scss' |
    'sh' |
    'sjs' |
    'smarty' |
    'soy_template' |
    'space' |
    'sql' |
    'sqlserver' |
    'stylus' |
    'svg' |
    'swift' |
    'swig' |
    'text' |
    'tsx' |
    'turtle' |
    'twig' |
    'typescript' |
    'velocity' |
    'verilog' |
    'vhdl' |
    'xml' |
    'yaml';

export const CodeLanguagesLabels: Record<CodeLanguage, string> = {
    actionscript: "ACTIONSCRIPT",
    apache_conf: "APACHE_CONF",
    applescript: "APPLESCRIPT",
    asciidoc: "ASCIIDOC",
    autohotkey: "AUTOHOTKEY",
    batchfile: "BATCHFILE",
    c9search: "C9SEARCH",
    clojure: "CLOJURE",
    cobol: "COBOL",
    coffee: "COFFEE",
    csharp: "CSHARP",
    css: "CSS",
    dart: "DART",
    dockerfile: "DOCKERFILE",
    dot: "DOT",
    elm: "ELM",
    erlang: "ERLANG",
    forth: "FORTH",
    fortran: "FORTRAN",
    ftl: "FTL",
    gcode: "GCODE",
    gherkin: "GHERKIN",
    gitignore: "GITIGNORE",
    glsl: "GLSL",
    golang: "GOLANG",
    groovy: "GROOVY",
    haml: "HAML",
    handlebars: "HANDLEBARS",
    haskell: "HASKELL",
    haxe: "HAXE",
    html: "HTML",
    ini: "INI",
    java: "JAVA",
    javascript: "JAVASCRIPT",
    json: "JSON",
    jsp: "JSP",
    jssm: "JSSM",
    jsx: "JSX",
    julia: "JULIA",
    kotlin: "KOTLIN",
    latex: "LATEX",
    lean: "LEAN",
    less: "LESS",
    liquid: "LIQUID",
    lisp: "LISP",
    livescript: "LIVESCRIPT",
    lucene: "LUCENE",
    makefile: "MAKEFILE",
    markdown: "MARKDOWN",
    mask: "MASK",
    matlab: "MATLAB",
    mavens_mate_log: "MAVENS_MATE_LOG",
    maze: "MAZE",
    mel: "MEL",
    mips_assembler: "MIPS_ASSEMBLER",
    mysql: "MYSQL",
    nix: "NIX",
    nsis: "NSIS",
    objectivec: "OBJECTIVEC",
    ocaml: "OCAML",
    pascal: "PASCAL",
    perl: "PERL",
    php: "PHP",
    plain_text: "PLAIN_TEXT",
    powershell: "POWERSHELL",
    praat: "PRAAT",
    prolog: "PROLOG",
    properties: "PROPERTIES",
    protobuf: "PROTOBUF",
    python: "PYTHON",
    r: "R",
    ruby: "RUBY",
    rust: "RUST",
    sass: "SASS",
    scad: "SCAD",
    scala: "SCALA",
    scheme: "SCHEME",
    scss: "SCSS",
    sh: "SH",
    sjs: "SJS",
    smarty: "SMARTY",
    soy_template: "SOY_TEMPLATE",
    space: "SPACE",
    sql: "SQL",
    sqlserver: "SQLSERVER",
    stylus: "STYLUS",
    svg: "SVG",
    swift: "SWIFT",
    swig: "SWIG",
    text: "TEXT",
    tsx: "TSX",
    turtle: "TURTLE",
    twig: "TWIG",
    typescript: "TYPESCRIPT",
    velocity: "VELOCITY",
    verilog: "VERILOG",
    vhdl: "VHDL",
    xml: "XML",
    yaml: "YAML"
}